// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/proto/wps.proto
// Protobuf Java Version: 4.27.1

public final class WpsOuterClass {
  private WpsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface WpsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Wps)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    java.util.List<WpsOuterClass.BSSID> 
        getBssidsList();
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    WpsOuterClass.BSSID getBssids(int index);
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    int getBssidsCount();

    /**
     * <code>optional int32 unknown1 = 3;</code>
     * @return Whether the unknown1 field is set.
     */
    boolean hasUnknown1();
    /**
     * <code>optional int32 unknown1 = 3;</code>
     * @return The unknown1.
     */
    int getUnknown1();

    /**
     * <code>int32 number_of_results = 4;</code>
     * @return The numberOfResults.
     */
    int getNumberOfResults();
  }
  /**
   * Protobuf type {@code Wps}
   */
  public  static final class Wps extends
      com.google.protobuf.GeneratedMessageLite<
          Wps, Wps.Builder> implements
      // @@protoc_insertion_point(message_implements:Wps)
      WpsOrBuilder {
    private Wps() {
      bssids_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int BSSIDS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<WpsOuterClass.BSSID> bssids_;
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    @java.lang.Override
    public java.util.List<WpsOuterClass.BSSID> getBssidsList() {
      return bssids_;
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    public java.util.List<? extends WpsOuterClass.BSSIDOrBuilder> 
        getBssidsOrBuilderList() {
      return bssids_;
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    @java.lang.Override
    public int getBssidsCount() {
      return bssids_.size();
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    @java.lang.Override
    public WpsOuterClass.BSSID getBssids(int index) {
      return bssids_.get(index);
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    public WpsOuterClass.BSSIDOrBuilder getBssidsOrBuilder(
        int index) {
      return bssids_.get(index);
    }
    private void ensureBssidsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<WpsOuterClass.BSSID> tmp = bssids_;
      if (!tmp.isModifiable()) {
        bssids_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    private void setBssids(
        int index, WpsOuterClass.BSSID value) {
      value.getClass();
  ensureBssidsIsMutable();
      bssids_.set(index, value);
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    private void addBssids(WpsOuterClass.BSSID value) {
      value.getClass();
  ensureBssidsIsMutable();
      bssids_.add(value);
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    private void addBssids(
        int index, WpsOuterClass.BSSID value) {
      value.getClass();
  ensureBssidsIsMutable();
      bssids_.add(index, value);
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    private void addAllBssids(
        java.lang.Iterable<? extends WpsOuterClass.BSSID> values) {
      ensureBssidsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, bssids_);
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    private void clearBssids() {
      bssids_ = emptyProtobufList();
    }
    /**
     * <code>repeated .BSSID bssids = 2;</code>
     */
    private void removeBssids(int index) {
      ensureBssidsIsMutable();
      bssids_.remove(index);
    }

    public static final int UNKNOWN1_FIELD_NUMBER = 3;
    private int unknown1_;
    /**
     * <code>optional int32 unknown1 = 3;</code>
     * @return Whether the unknown1 field is set.
     */
    @java.lang.Override
    public boolean hasUnknown1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 unknown1 = 3;</code>
     * @return The unknown1.
     */
    @java.lang.Override
    public int getUnknown1() {
      return unknown1_;
    }
    /**
     * <code>optional int32 unknown1 = 3;</code>
     * @param value The unknown1 to set.
     */
    private void setUnknown1(int value) {
      bitField0_ |= 0x00000001;
      unknown1_ = value;
    }
    /**
     * <code>optional int32 unknown1 = 3;</code>
     */
    private void clearUnknown1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      unknown1_ = 0;
    }

    public static final int NUMBER_OF_RESULTS_FIELD_NUMBER = 4;
    private int numberOfResults_;
    /**
     * <code>int32 number_of_results = 4;</code>
     * @return The numberOfResults.
     */
    @java.lang.Override
    public int getNumberOfResults() {
      return numberOfResults_;
    }
    /**
     * <code>int32 number_of_results = 4;</code>
     * @param value The numberOfResults to set.
     */
    private void setNumberOfResults(int value) {
      
      numberOfResults_ = value;
    }
    /**
     * <code>int32 number_of_results = 4;</code>
     */
    private void clearNumberOfResults() {

      numberOfResults_ = 0;
    }

    public static WpsOuterClass.Wps parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.Wps parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.Wps parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.Wps parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.Wps parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.Wps parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.Wps parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WpsOuterClass.Wps parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static WpsOuterClass.Wps parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static WpsOuterClass.Wps parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WpsOuterClass.Wps parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WpsOuterClass.Wps parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(WpsOuterClass.Wps prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Wps}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          WpsOuterClass.Wps, Builder> implements
        // @@protoc_insertion_point(builder_implements:Wps)
        WpsOuterClass.WpsOrBuilder {
      // Construct using WpsOuterClass.Wps.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      @java.lang.Override
      public java.util.List<WpsOuterClass.BSSID> getBssidsList() {
        return java.util.Collections.unmodifiableList(
            instance.getBssidsList());
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      @java.lang.Override
      public int getBssidsCount() {
        return instance.getBssidsCount();
      }/**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      @java.lang.Override
      public WpsOuterClass.BSSID getBssids(int index) {
        return instance.getBssids(index);
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder setBssids(
          int index, WpsOuterClass.BSSID value) {
        copyOnWrite();
        instance.setBssids(index, value);
        return this;
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder setBssids(
          int index, WpsOuterClass.BSSID.Builder builderForValue) {
        copyOnWrite();
        instance.setBssids(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder addBssids(WpsOuterClass.BSSID value) {
        copyOnWrite();
        instance.addBssids(value);
        return this;
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder addBssids(
          int index, WpsOuterClass.BSSID value) {
        copyOnWrite();
        instance.addBssids(index, value);
        return this;
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder addBssids(
          WpsOuterClass.BSSID.Builder builderForValue) {
        copyOnWrite();
        instance.addBssids(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder addBssids(
          int index, WpsOuterClass.BSSID.Builder builderForValue) {
        copyOnWrite();
        instance.addBssids(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder addAllBssids(
          java.lang.Iterable<? extends WpsOuterClass.BSSID> values) {
        copyOnWrite();
        instance.addAllBssids(values);
        return this;
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder clearBssids() {
        copyOnWrite();
        instance.clearBssids();
        return this;
      }
      /**
       * <code>repeated .BSSID bssids = 2;</code>
       */
      public Builder removeBssids(int index) {
        copyOnWrite();
        instance.removeBssids(index);
        return this;
      }

      /**
       * <code>optional int32 unknown1 = 3;</code>
       * @return Whether the unknown1 field is set.
       */
      @java.lang.Override
      public boolean hasUnknown1() {
        return instance.hasUnknown1();
      }
      /**
       * <code>optional int32 unknown1 = 3;</code>
       * @return The unknown1.
       */
      @java.lang.Override
      public int getUnknown1() {
        return instance.getUnknown1();
      }
      /**
       * <code>optional int32 unknown1 = 3;</code>
       * @param value The unknown1 to set.
       * @return This builder for chaining.
       */
      public Builder setUnknown1(int value) {
        copyOnWrite();
        instance.setUnknown1(value);
        return this;
      }
      /**
       * <code>optional int32 unknown1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnknown1() {
        copyOnWrite();
        instance.clearUnknown1();
        return this;
      }

      /**
       * <code>int32 number_of_results = 4;</code>
       * @return The numberOfResults.
       */
      @java.lang.Override
      public int getNumberOfResults() {
        return instance.getNumberOfResults();
      }
      /**
       * <code>int32 number_of_results = 4;</code>
       * @param value The numberOfResults to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfResults(int value) {
        copyOnWrite();
        instance.setNumberOfResults(value);
        return this;
      }
      /**
       * <code>int32 number_of_results = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfResults() {
        copyOnWrite();
        instance.clearNumberOfResults();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Wps)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new WpsOuterClass.Wps();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "bssids_",
              WpsOuterClass.BSSID.class,
              "unknown1_",
              "numberOfResults_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0001\u0002\u0004\u0003\u0000\u0001\u0000\u0002\u001b\u0003\u1004" +
                "\u0000\u0004\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<WpsOuterClass.Wps> parser = PARSER;
          if (parser == null) {
            synchronized (WpsOuterClass.Wps.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<WpsOuterClass.Wps>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Wps)
    private static final WpsOuterClass.Wps DEFAULT_INSTANCE;
    static {
      Wps defaultInstance = new Wps();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Wps.class, defaultInstance);
    }

    public static WpsOuterClass.Wps getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Wps> PARSER;

    public static com.google.protobuf.Parser<Wps> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface BSSIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BSSID)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string mac = 1;</code>
     * @return The mac.
     */
    java.lang.String getMac();
    /**
     * <code>string mac = 1;</code>
     * @return The bytes for mac.
     */
    com.google.protobuf.ByteString
        getMacBytes();

    /**
     * <code>.PositioningInfo positioning_info = 2;</code>
     * @return Whether the positioningInfo field is set.
     */
    boolean hasPositioningInfo();
    /**
     * <code>.PositioningInfo positioning_info = 2;</code>
     * @return The positioningInfo.
     */
    WpsOuterClass.PositioningInfo getPositioningInfo();

    /**
     * <code>int32 channel = 21;</code>
     * @return The channel.
     */
    int getChannel();
  }
  /**
   * Protobuf type {@code BSSID}
   */
  public  static final class BSSID extends
      com.google.protobuf.GeneratedMessageLite<
          BSSID, BSSID.Builder> implements
      // @@protoc_insertion_point(message_implements:BSSID)
      BSSIDOrBuilder {
    private BSSID() {
      mac_ = "";
    }
    private int bitField0_;
    public static final int MAC_FIELD_NUMBER = 1;
    private java.lang.String mac_;
    /**
     * <code>string mac = 1;</code>
     * @return The mac.
     */
    @java.lang.Override
    public java.lang.String getMac() {
      return mac_;
    }
    /**
     * <code>string mac = 1;</code>
     * @return The bytes for mac.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMacBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mac_);
    }
    /**
     * <code>string mac = 1;</code>
     * @param value The mac to set.
     */
    private void setMac(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      mac_ = value;
    }
    /**
     * <code>string mac = 1;</code>
     */
    private void clearMac() {

      mac_ = getDefaultInstance().getMac();
    }
    /**
     * <code>string mac = 1;</code>
     * @param value The bytes for mac to set.
     */
    private void setMacBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      mac_ = value.toStringUtf8();

    }

    public static final int POSITIONING_INFO_FIELD_NUMBER = 2;
    private WpsOuterClass.PositioningInfo positioningInfo_;
    /**
     * <code>.PositioningInfo positioning_info = 2;</code>
     */
    @java.lang.Override
    public boolean hasPositioningInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.PositioningInfo positioning_info = 2;</code>
     */
    @java.lang.Override
    public WpsOuterClass.PositioningInfo getPositioningInfo() {
      return positioningInfo_ == null ? WpsOuterClass.PositioningInfo.getDefaultInstance() : positioningInfo_;
    }
    /**
     * <code>.PositioningInfo positioning_info = 2;</code>
     */
    private void setPositioningInfo(WpsOuterClass.PositioningInfo value) {
      value.getClass();
  positioningInfo_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.PositioningInfo positioning_info = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergePositioningInfo(WpsOuterClass.PositioningInfo value) {
      value.getClass();
  if (positioningInfo_ != null &&
          positioningInfo_ != WpsOuterClass.PositioningInfo.getDefaultInstance()) {
        positioningInfo_ =
          WpsOuterClass.PositioningInfo.newBuilder(positioningInfo_).mergeFrom(value).buildPartial();
      } else {
        positioningInfo_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.PositioningInfo positioning_info = 2;</code>
     */
    private void clearPositioningInfo() {  positioningInfo_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int CHANNEL_FIELD_NUMBER = 21;
    private int channel_;
    /**
     * <code>int32 channel = 21;</code>
     * @return The channel.
     */
    @java.lang.Override
    public int getChannel() {
      return channel_;
    }
    /**
     * <code>int32 channel = 21;</code>
     * @param value The channel to set.
     */
    private void setChannel(int value) {
      
      channel_ = value;
    }
    /**
     * <code>int32 channel = 21;</code>
     */
    private void clearChannel() {

      channel_ = 0;
    }

    public static WpsOuterClass.BSSID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.BSSID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.BSSID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.BSSID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.BSSID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.BSSID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.BSSID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WpsOuterClass.BSSID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static WpsOuterClass.BSSID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static WpsOuterClass.BSSID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WpsOuterClass.BSSID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WpsOuterClass.BSSID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(WpsOuterClass.BSSID prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code BSSID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          WpsOuterClass.BSSID, Builder> implements
        // @@protoc_insertion_point(builder_implements:BSSID)
        WpsOuterClass.BSSIDOrBuilder {
      // Construct using WpsOuterClass.BSSID.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string mac = 1;</code>
       * @return The mac.
       */
      @java.lang.Override
      public java.lang.String getMac() {
        return instance.getMac();
      }
      /**
       * <code>string mac = 1;</code>
       * @return The bytes for mac.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMacBytes() {
        return instance.getMacBytes();
      }
      /**
       * <code>string mac = 1;</code>
       * @param value The mac to set.
       * @return This builder for chaining.
       */
      public Builder setMac(
          java.lang.String value) {
        copyOnWrite();
        instance.setMac(value);
        return this;
      }
      /**
       * <code>string mac = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMac() {
        copyOnWrite();
        instance.clearMac();
        return this;
      }
      /**
       * <code>string mac = 1;</code>
       * @param value The bytes for mac to set.
       * @return This builder for chaining.
       */
      public Builder setMacBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMacBytes(value);
        return this;
      }

      /**
       * <code>.PositioningInfo positioning_info = 2;</code>
       */
      @java.lang.Override
      public boolean hasPositioningInfo() {
        return instance.hasPositioningInfo();
      }
      /**
       * <code>.PositioningInfo positioning_info = 2;</code>
       */
      @java.lang.Override
      public WpsOuterClass.PositioningInfo getPositioningInfo() {
        return instance.getPositioningInfo();
      }
      /**
       * <code>.PositioningInfo positioning_info = 2;</code>
       */
      public Builder setPositioningInfo(WpsOuterClass.PositioningInfo value) {
        copyOnWrite();
        instance.setPositioningInfo(value);
        return this;
        }
      /**
       * <code>.PositioningInfo positioning_info = 2;</code>
       */
      public Builder setPositioningInfo(
          WpsOuterClass.PositioningInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setPositioningInfo(builderForValue.build());
        return this;
      }
      /**
       * <code>.PositioningInfo positioning_info = 2;</code>
       */
      public Builder mergePositioningInfo(WpsOuterClass.PositioningInfo value) {
        copyOnWrite();
        instance.mergePositioningInfo(value);
        return this;
      }
      /**
       * <code>.PositioningInfo positioning_info = 2;</code>
       */
      public Builder clearPositioningInfo() {  copyOnWrite();
        instance.clearPositioningInfo();
        return this;
      }

      /**
       * <code>int32 channel = 21;</code>
       * @return The channel.
       */
      @java.lang.Override
      public int getChannel() {
        return instance.getChannel();
      }
      /**
       * <code>int32 channel = 21;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(int value) {
        copyOnWrite();
        instance.setChannel(value);
        return this;
      }
      /**
       * <code>int32 channel = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        copyOnWrite();
        instance.clearChannel();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BSSID)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new WpsOuterClass.BSSID();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "mac_",
              "positioningInfo_",
              "channel_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0001\u0001\u0015\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
                "\u0000\u0015\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<WpsOuterClass.BSSID> parser = PARSER;
          if (parser == null) {
            synchronized (WpsOuterClass.BSSID.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<WpsOuterClass.BSSID>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:BSSID)
    private static final WpsOuterClass.BSSID DEFAULT_INSTANCE;
    static {
      BSSID defaultInstance = new BSSID();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        BSSID.class, defaultInstance);
    }

    public static WpsOuterClass.BSSID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BSSID> PARSER;

    public static com.google.protobuf.Parser<BSSID> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PositioningInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PositioningInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 latitude = 1;</code>
     * @return The latitude.
     */
    long getLatitude();

    /**
     * <code>int64 longitude = 2;</code>
     * @return The longitude.
     */
    long getLongitude();

    /**
     * <code>int64 accuracy = 3;</code>
     * @return The accuracy.
     */
    long getAccuracy();

    /**
     * <code>int64 unknown1 = 4;</code>
     * @return The unknown1.
     */
    long getUnknown1();

    /**
     * <code>int64 unknown2 = 5;</code>
     * @return The unknown2.
     */
    long getUnknown2();

    /**
     * <code>int64 unknown3 = 6;</code>
     * @return The unknown3.
     */
    long getUnknown3();

    /**
     * <code>int64 unknown4 = 11;</code>
     * @return The unknown4.
     */
    long getUnknown4();

    /**
     * <code>int64 unknown5 = 12;</code>
     * @return The unknown5.
     */
    long getUnknown5();
  }
  /**
   * Protobuf type {@code PositioningInfo}
   */
  public  static final class PositioningInfo extends
      com.google.protobuf.GeneratedMessageLite<
          PositioningInfo, PositioningInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:PositioningInfo)
      PositioningInfoOrBuilder {
    private PositioningInfo() {
    }
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private long latitude_;
    /**
     * <code>int64 latitude = 1;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public long getLatitude() {
      return latitude_;
    }
    /**
     * <code>int64 latitude = 1;</code>
     * @param value The latitude to set.
     */
    private void setLatitude(long value) {
      
      latitude_ = value;
    }
    /**
     * <code>int64 latitude = 1;</code>
     */
    private void clearLatitude() {

      latitude_ = 0L;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private long longitude_;
    /**
     * <code>int64 longitude = 2;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public long getLongitude() {
      return longitude_;
    }
    /**
     * <code>int64 longitude = 2;</code>
     * @param value The longitude to set.
     */
    private void setLongitude(long value) {
      
      longitude_ = value;
    }
    /**
     * <code>int64 longitude = 2;</code>
     */
    private void clearLongitude() {

      longitude_ = 0L;
    }

    public static final int ACCURACY_FIELD_NUMBER = 3;
    private long accuracy_;
    /**
     * <code>int64 accuracy = 3;</code>
     * @return The accuracy.
     */
    @java.lang.Override
    public long getAccuracy() {
      return accuracy_;
    }
    /**
     * <code>int64 accuracy = 3;</code>
     * @param value The accuracy to set.
     */
    private void setAccuracy(long value) {
      
      accuracy_ = value;
    }
    /**
     * <code>int64 accuracy = 3;</code>
     */
    private void clearAccuracy() {

      accuracy_ = 0L;
    }

    public static final int UNKNOWN1_FIELD_NUMBER = 4;
    private long unknown1_;
    /**
     * <code>int64 unknown1 = 4;</code>
     * @return The unknown1.
     */
    @java.lang.Override
    public long getUnknown1() {
      return unknown1_;
    }
    /**
     * <code>int64 unknown1 = 4;</code>
     * @param value The unknown1 to set.
     */
    private void setUnknown1(long value) {
      
      unknown1_ = value;
    }
    /**
     * <code>int64 unknown1 = 4;</code>
     */
    private void clearUnknown1() {

      unknown1_ = 0L;
    }

    public static final int UNKNOWN2_FIELD_NUMBER = 5;
    private long unknown2_;
    /**
     * <code>int64 unknown2 = 5;</code>
     * @return The unknown2.
     */
    @java.lang.Override
    public long getUnknown2() {
      return unknown2_;
    }
    /**
     * <code>int64 unknown2 = 5;</code>
     * @param value The unknown2 to set.
     */
    private void setUnknown2(long value) {
      
      unknown2_ = value;
    }
    /**
     * <code>int64 unknown2 = 5;</code>
     */
    private void clearUnknown2() {

      unknown2_ = 0L;
    }

    public static final int UNKNOWN3_FIELD_NUMBER = 6;
    private long unknown3_;
    /**
     * <code>int64 unknown3 = 6;</code>
     * @return The unknown3.
     */
    @java.lang.Override
    public long getUnknown3() {
      return unknown3_;
    }
    /**
     * <code>int64 unknown3 = 6;</code>
     * @param value The unknown3 to set.
     */
    private void setUnknown3(long value) {
      
      unknown3_ = value;
    }
    /**
     * <code>int64 unknown3 = 6;</code>
     */
    private void clearUnknown3() {

      unknown3_ = 0L;
    }

    public static final int UNKNOWN4_FIELD_NUMBER = 11;
    private long unknown4_;
    /**
     * <code>int64 unknown4 = 11;</code>
     * @return The unknown4.
     */
    @java.lang.Override
    public long getUnknown4() {
      return unknown4_;
    }
    /**
     * <code>int64 unknown4 = 11;</code>
     * @param value The unknown4 to set.
     */
    private void setUnknown4(long value) {
      
      unknown4_ = value;
    }
    /**
     * <code>int64 unknown4 = 11;</code>
     */
    private void clearUnknown4() {

      unknown4_ = 0L;
    }

    public static final int UNKNOWN5_FIELD_NUMBER = 12;
    private long unknown5_;
    /**
     * <code>int64 unknown5 = 12;</code>
     * @return The unknown5.
     */
    @java.lang.Override
    public long getUnknown5() {
      return unknown5_;
    }
    /**
     * <code>int64 unknown5 = 12;</code>
     * @param value The unknown5 to set.
     */
    private void setUnknown5(long value) {
      
      unknown5_ = value;
    }
    /**
     * <code>int64 unknown5 = 12;</code>
     */
    private void clearUnknown5() {

      unknown5_ = 0L;
    }

    public static WpsOuterClass.PositioningInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static WpsOuterClass.PositioningInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static WpsOuterClass.PositioningInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WpsOuterClass.PositioningInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(WpsOuterClass.PositioningInfo prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code PositioningInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          WpsOuterClass.PositioningInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:PositioningInfo)
        WpsOuterClass.PositioningInfoOrBuilder {
      // Construct using WpsOuterClass.PositioningInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 latitude = 1;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public long getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>int64 latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(long value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>int64 latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>int64 longitude = 2;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public long getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>int64 longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(long value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>int64 longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      /**
       * <code>int64 accuracy = 3;</code>
       * @return The accuracy.
       */
      @java.lang.Override
      public long getAccuracy() {
        return instance.getAccuracy();
      }
      /**
       * <code>int64 accuracy = 3;</code>
       * @param value The accuracy to set.
       * @return This builder for chaining.
       */
      public Builder setAccuracy(long value) {
        copyOnWrite();
        instance.setAccuracy(value);
        return this;
      }
      /**
       * <code>int64 accuracy = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccuracy() {
        copyOnWrite();
        instance.clearAccuracy();
        return this;
      }

      /**
       * <code>int64 unknown1 = 4;</code>
       * @return The unknown1.
       */
      @java.lang.Override
      public long getUnknown1() {
        return instance.getUnknown1();
      }
      /**
       * <code>int64 unknown1 = 4;</code>
       * @param value The unknown1 to set.
       * @return This builder for chaining.
       */
      public Builder setUnknown1(long value) {
        copyOnWrite();
        instance.setUnknown1(value);
        return this;
      }
      /**
       * <code>int64 unknown1 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnknown1() {
        copyOnWrite();
        instance.clearUnknown1();
        return this;
      }

      /**
       * <code>int64 unknown2 = 5;</code>
       * @return The unknown2.
       */
      @java.lang.Override
      public long getUnknown2() {
        return instance.getUnknown2();
      }
      /**
       * <code>int64 unknown2 = 5;</code>
       * @param value The unknown2 to set.
       * @return This builder for chaining.
       */
      public Builder setUnknown2(long value) {
        copyOnWrite();
        instance.setUnknown2(value);
        return this;
      }
      /**
       * <code>int64 unknown2 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnknown2() {
        copyOnWrite();
        instance.clearUnknown2();
        return this;
      }

      /**
       * <code>int64 unknown3 = 6;</code>
       * @return The unknown3.
       */
      @java.lang.Override
      public long getUnknown3() {
        return instance.getUnknown3();
      }
      /**
       * <code>int64 unknown3 = 6;</code>
       * @param value The unknown3 to set.
       * @return This builder for chaining.
       */
      public Builder setUnknown3(long value) {
        copyOnWrite();
        instance.setUnknown3(value);
        return this;
      }
      /**
       * <code>int64 unknown3 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnknown3() {
        copyOnWrite();
        instance.clearUnknown3();
        return this;
      }

      /**
       * <code>int64 unknown4 = 11;</code>
       * @return The unknown4.
       */
      @java.lang.Override
      public long getUnknown4() {
        return instance.getUnknown4();
      }
      /**
       * <code>int64 unknown4 = 11;</code>
       * @param value The unknown4 to set.
       * @return This builder for chaining.
       */
      public Builder setUnknown4(long value) {
        copyOnWrite();
        instance.setUnknown4(value);
        return this;
      }
      /**
       * <code>int64 unknown4 = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnknown4() {
        copyOnWrite();
        instance.clearUnknown4();
        return this;
      }

      /**
       * <code>int64 unknown5 = 12;</code>
       * @return The unknown5.
       */
      @java.lang.Override
      public long getUnknown5() {
        return instance.getUnknown5();
      }
      /**
       * <code>int64 unknown5 = 12;</code>
       * @param value The unknown5 to set.
       * @return This builder for chaining.
       */
      public Builder setUnknown5(long value) {
        copyOnWrite();
        instance.setUnknown5(value);
        return this;
      }
      /**
       * <code>int64 unknown5 = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnknown5() {
        copyOnWrite();
        instance.clearUnknown5();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PositioningInfo)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new WpsOuterClass.PositioningInfo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "latitude_",
              "longitude_",
              "accuracy_",
              "unknown1_",
              "unknown2_",
              "unknown3_",
              "unknown4_",
              "unknown5_",
            };
            java.lang.String info =
                "\u0000\b\u0000\u0000\u0001\f\b\u0000\u0000\u0000\u0001\u0002\u0002\u0002\u0003\u0002" +
                "\u0004\u0002\u0005\u0002\u0006\u0002\u000b\u0002\f\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<WpsOuterClass.PositioningInfo> parser = PARSER;
          if (parser == null) {
            synchronized (WpsOuterClass.PositioningInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<WpsOuterClass.PositioningInfo>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:PositioningInfo)
    private static final WpsOuterClass.PositioningInfo DEFAULT_INSTANCE;
    static {
      PositioningInfo defaultInstance = new PositioningInfo();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PositioningInfo.class, defaultInstance);
    }

    public static WpsOuterClass.PositioningInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PositioningInfo> PARSER;

    public static com.google.protobuf.Parser<PositioningInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
